# shared between all clients
management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all actuator endpoints

logging:
  level:
    root: info # root logging level

spring:
  jackson:
    serialization:
      indent_output: true # pretty print JSON responses
  lifecycle:
    timeout-per-shutdown-phase: 5s # shutdown timeout

server:
  shutdown: graceful # enable graceful shutdown