# shared between all clients
management:
  endpoints:
    web:
      exposure:
        include: * # expose all actuator endpoints

logging:
  level:
    root: info # root logging level

spring:
  jackson:
    serialization:
      indent_output: true # pretty print JSON responses