# shared between all clients
management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all actuator endpoints

logging:
  level:
    root: info # root logging level

spring:
  jackson:
    serialization:
      indent_output: true # pretty print JSON responses

  lifecycle:
    timeout-per-shutdown-phase: 5s # shutdown timeout

  # to throw exception if page not found instead of whitelabel page
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: true
  resources:
    add-mappings: false

server:
  shutdown: graceful # enable graceful shutdown

  # disable whitelabel error page
  error:
    whitelabel:
      enabled: false
